"""Initial migration

Revision ID: da3cbaf1daec
Revises: 
Create Date: 2026-03-01 00:00:28.291314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3cbaf1daec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price_coins', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_store_items_id'), 'store_items', ['id'], unique=False)
    op.create_table('quest_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('sessions_in_stage', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_progress_id'), 'quest_progress', ['id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_key', sa.String(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_table('user_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_inventory_id'), 'user_inventory', ['id'], unique=False)
    op.add_column('session_questions', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('user_character_progress', sa.Column('easiness_factor', sa.Float(), nullable=True))
    op.add_column('user_character_progress', sa.Column('sm2_interval', sa.Integer(), nullable=True))
    op.add_column('user_character_progress', sa.Column('sm2_repetitions', sa.Integer(), nullable=True))
    op.add_column('user_character_progress', sa.Column('next_review_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('streak_freezes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('best_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('perfect_sessions', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_sessions_completed', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('car_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('equipped_car_skin', sa.String(), nullable=True))
    op.add_column('users', sa.Column('equipped_background', sa.String(), nullable=True))
    op.add_column('users', sa.Column('equipped_trail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'equipped_trail')
    op.drop_column('users', 'equipped_background')
    op.drop_column('users', 'equipped_car_skin')
    op.drop_column('users', 'car_level')
    op.drop_column('users', 'total_sessions_completed')
    op.drop_column('users', 'perfect_sessions')
    op.drop_column('users', 'best_streak')
    op.drop_column('users', 'streak_freezes')
    op.drop_column('user_character_progress', 'next_review_date')
    op.drop_column('user_character_progress', 'sm2_repetitions')
    op.drop_column('user_character_progress', 'sm2_interval')
    op.drop_column('user_character_progress', 'easiness_factor')
    op.drop_column('session_questions', 'started_at')
    op.drop_index(op.f('ix_user_inventory_id'), table_name='user_inventory')
    op.drop_table('user_inventory')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_quest_progress_id'), table_name='quest_progress')
    op.drop_table('quest_progress')
    op.drop_index(op.f('ix_store_items_id'), table_name='store_items')
    op.drop_table('store_items')
    # ### end Alembic commands ###
